#pragma clang diagnostic ignored "-Wshorten-64-to-32"
#pragma clang diagnostic ignored "-Wunused-variable"

#include "api.h"
#include "fe_0.c"
#include "fe_1.c"
#include "fe_add.c"
#include "fe_cmov.c"
#include "fe_copy.c"
#include "fe_cswap.c"
#include "fe_frombytes.c"
#include "fe_invert.c"
#include "fe_isnegative.c"
#include "fe_mul.c"
#include "fe_mul121666.c"
#include "fe_sq_mul.c"
#include "fe_sq.c"
#include "fe_sq2.c"
#include "fe_sub.c"
#include "fe_tobytes.c"
#include "ge_add.c"
#include "ge_p1p1_to_p2.c"
#include "ge_p1p1_to_p3.c"
#include "ge_p2_dbl.c"
#include "ge_p3_to_cached.c"
#include "ge_p3_tobytes.c"
#include "ge_scalarmult_base.c"
#include "sc_muladd.c"
#include "sc_reduce.c"
#include "sc_reduce_carry.c"
#include "sc_reduce_internal.c"
#include "keypair.c"
#include "scalarmult.c"
#include "sign.c"
